# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.synced_folder "src/", "/srv/website"
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end


  config.vm.define :clienteUbuntu do |clienteUbuntu|
    clienteUbuntu.vm.box = "jandresjn/jandresjn"
    clienteUbuntu.vm.box_version = "1.1"
    clienteUbuntu.vm.network :private_network, ip: "192.168.100.2"
    clienteUbuntu.vm.hostname = "clienteUbuntu"
    #clienteUbuntu.vm.provision "shell", inline: 'export PATH="$HOME/.local/bin:$PATH"'

  end

  config.vm.define :servidorUbuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "jandresjn/jandresjn"
    servidorUbuntu.vm.box_version = "1.1"
    servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
    servidorUbuntu.vm.hostname = "servidorUbuntu"
    #servidorUbuntu.vm.provision "shell", inline: 'export PATH="$HOME/.local/bin:$PATH"'
  end

end